name: InventorySwitch
main: com.vilsol.inventoryswitch.InventorySwitch
version: 2.4
dev-url: http://dev.bukkit.org/server-mods/inventoryswitch/
commands:
   is:
      description: The InventorySwitch command.
      usage: /<command> <get/set/del/help> [inventory]
permissions:
    inventoryswitch.*:
        description: Gives access to all InventorySwitch commands
        children:
            inventoryswitch.get: true
            inventoryswitch.set: true
            inventoryswitch.del: true
    inventoryswitch.get:
        description: Allows you to retrieve an inventory.
        default: op
    inventoryswitch.set:
        description: Allows you to set an inventory.
        default: op
    inventoryswitch.del:
        description: Allows you to give an inventory.
        default: op